services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - data-network
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - data-network
  
  ingestion:
    build: ./containers-docker/ingestion
    container_name: ingestion
    depends_on:
    - mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_HOST=mongodb
      - SOCRATA_APP_TOKEN=${SOCRATA_APP_TOKEN}
      - SOCRATA_APP_USER=${SOCRATA_APP_USER}
      - SOCRATA_APP_PWD=${SOCRATA_APP_PWD}
    networks:
      - data-network
    command: tail -f /dev/null # Remove when up to cloud

  spark-jupyter:
    build: ./containers-docker/nb-spark
    container_name: spark-jupyter
    depends_on:
      - mongodb
      - minio
    ports:
      - "8888:8888" 
      - "4040:4040" 
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - SPARK_OPTS=--packages io.delta:delta-core_2.12:2.4.0,org.mongodb.spark:mongo-spark-connector_2.12:10.2.0,org.apache.hadoop:hadoop-aws:3.3.4
    networks:
      - data-network

volumes:
  mongo_data:
  minio_data:

networks:
  data-network:
    driver: bridge